### ISSUE TITLE
[For discussion] Type & space scales

### ISSUE THREAD

**Issue by colepeters** [enhance-dev/enhance-styles#14]
Something I'm finding a bit finicky is landing on a scale that works equally well for both type sizes and layout spacing, as they both currently use the same scale intervals via `styleguide.json`. (This isn't a challenge unique to Enhance Styles, I've faced this many times with other parametric design implementations.)

Specifically, I find that things get tough as the scale moves into the negative values (`text-1`, `text-2`, etc). The values produced by certain scales at these intervals often results in type sizes that make legibility a challenge; however, those same values can be really useful for fine tuning layouts. Here's an example:

```css
.text5{font-size:3.052rem;}/* 48.828px */ 
.text4{font-size:2.441rem;}/* 39.063px */ 
.text3{font-size:1.953rem;}/* 31.25px */ 
.text2{font-size:1.563rem;}/* 25px */ 
.text1{font-size:1.25rem;}/* 20px */ 
.text0{font-size:1rem;}/* 16px */ 
.text-1{font-size:0.8rem;}/* 12.8px */ 
.text-2{font-size:0.64rem;}/* 10.24px */ 
.text-3{font-size:0.512rem;}/* 8.192px */ 
.text-4{font-size:0.41rem;}/* 6.554px */ 
.text-5{font-size:0.328rem;}/* 5.243px */ 
```

In this instance, the positive intervals (`text1`, `text2`…) work well, but the negative intervals would make most type too hard to read. On the flip side, those same intervals can make precise adjustments to margins, padding, etc where needed, which is nice.

One workaround that I've tried is using a scale with very small intervals (for example, a minor third scale, with a 1.2 scale factor), which produces finer gradations (and thus more usable type sizes at the negative intervals). However, depending on the number of steps specified in the scale, this can produce either too few distinct options for type sizing at positive intervals (since the contrast between heading level sizes is quite minimal), or too many superfluous options for both type and layout spacing (thus reducing the effectiveness of using a parametric bounds in the first place, since many of the values produced will go unused).

One option that comes to mind is the ability to provide explicit intervals for the scale, and possibly the option to differentiate the type and layout scales. The existing `scale` configuration option could be persisted, but a new set of options could be provided as opt ins for folks who want to get more granular. For example:

```json
{
  "typeScale": [
    "0.875rem",
    "1rem",
    "1.25rem",
    "1.563rem",
    "1.953rem",
    "…"
  ],
  "spaceScale": {
    "ratio": "perfectFourth",
    "steps": 16
  }
}
```

In this example, both `typeScale` and `spaceScale` could take either an array of explicit values, or an object to specify a generated scale, as the existing `scale` option currently works.

This is just one idea off the top of my head, but wanted to spin up an issue to get the wheels turning. All input welcome!
